{{- if .Values.backend.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "todo-chatbot.fullname" . }}-backend-secret
  labels:
    {{- include "todo-chatbot.backend.labels" . | nindent 4 }}
type: Opaque
data:
  DATABASE_URL: {{ .Values.backend.secrets.DATABASE_URL | b64enc | quote }}
  BETTER_AUTH_SECRET: {{ .Values.backend.secrets.BETTER_AUTH_SECRET | b64enc | quote }}
  NEXT_PUBLIC_OPENROUTER_KEY: {{ .Values.backend.secrets.NEXT_PUBLIC_OPENROUTER_KEY | b64enc | quote }}
{{- end }}
